### PR TITLE
Dockerfile updated to pass all the Red Hat Certification requirements

### PR DESCRIPTION
**Pull request by manojjahgirdar**
The Dockerfile now passes all the following Tests on Red Hat Certification:
- [x] `is_rhel`
- [x] `has_licenses`
- [x] `rpm_list_successful`
- [x] `not_running_privileged`
- [x] `not_running_as_root`
- [x] `name_label_exists`
- [x] `vendor_label_exists`
- [x] `version_label_exists`
- [x] `release_label_exists`
- [x] `good_tags`
- [x] `good_layer_count`
- [x] `free_of_critical_vulnerabilities`
- [x] `free_of_important_vulnerabilities`
- [x] `non_inherited_base_label_name`
- [x] `non_inherited_base_label_vendor`
- [x] `non_inherited_base_label_description`
- [x] `non_inherited_base_label_summary`
- [x] `has_base_rh_image`
- [x] `ubi_content_ok`
- [x] `has_under_40_layers`

>Note: At times the tests `free_of_critical_vulnerabilities` or `free_of_important_vulnerabilities` may fail if the `ubi8/nodejs-12` has any [known vulnerability](https://catalog.redhat.com/software/containers/ubi8/nodejs-12/5d3fff015a13461f5fb8635a?gti-tabs=unauthenticated&container-tabs=security).

### CODE REVIEW

**Comment by bwoolf1** [comment]
LGTM. Nice job.

@csantanapr:
- This is built from ubi8/nodejs-12. Do you want to build it from ubi8/nodejs-14?
- Do you want the security update command commented out or not commented out by default?
- What do you think of the default values for version and release being the same as those for the UBI the image is built from?

**Comment by mjperrins** [comment]
Brilliant work !!

**Comment by bwoolf1** [comment]
@csantanapr: What updates do you want to this PR to approve it? Please document these requests for @manojjahgirdar. Thanks.

**Comment by manojjahgirdar** [comment]
- I have commented the updating image security content command.
- I have updated the base image to `ubi8/nodejs14:1-28`.
- Here is a confirmation that the Dockerfile builds successfully after the improvements:
Screenshot 2021-05-05 at 1 41 44 PM

**Comment by csantanapr** [comment]
Please verify the app still works on OpenShift, you can run the Toolkit pipeline

**Comment by manojjahgirdar** [comment]
> Please verify the app still works on OpenShift, you can run the Toolkit pipeline

@csantanapr,
This passes all the tests except for the `gitops` one. The logs says the following:
```
unable to find result referenced by param "helm-url" in "gitops": Could not find result with name helm-url for task run helm-release
```
Screenshot 2021-05-05 at 9 52 06 PM

what does this mean?

**Comment by manojjahgirdar** [comment]
> Please verify the app still works on OpenShift, you can run the Toolkit pipeline

@csantanapr, Here is the verification that the app still works on OpenShift, using the Toolkit pipeline to build and deploy.
Screenshot 2021-05-06 at 11 50 29 PM

**Comment by manojjahgirdar** [comment]
@csantanapr Vulnerability Advisor now finds no issues, here is proof.
Screenshot 2021-05-07 at 10 15 12 PM

**Review by csantanapr — APPROVED** [review]
thanks
LGTM

**Pull request merged**
